# Generated by Django 4.0.5 on 2022-06-20 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionType',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('logo', models.CharField(blank=True, max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('round_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.UUIDField(primary_key=True, serialize=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.candidate')),
                ('submissions', models.ManyToManyField(to='elections.round')),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('election_id', models.IntegerField(primary_key=True, serialize=False)),
                ('progress', models.ManyToManyField(to='elections.round')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.electiontype')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='elections',
            field=models.ManyToManyField(to='elections.election'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.party'),
        ),
    ]
