# Generated by Django 4.0.5 on 2022-06-16 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('surname', models.CharField(blank=True, max_length=200)),
                ('website', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('election_id', models.UUIDField(default=0, primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionType',
            fields=[
                ('type_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('logo', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('round_id', models.UUIDField(primary_key=True, serialize=False)),
                ('election_date', models.DateField(blank=True)),
                ('number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.UUIDField(primary_key=True, serialize=False)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.round')),
                ('vote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.vote')),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.electiontype')),
                ('voter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.candidate')),
                ('election_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.round')),
                ('voter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election')),
                ('round_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.round')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='party_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.party'),
        ),
    ]
