# Generated by Django 4.0.5 on 2022-06-16 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='election',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='electionprogress',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='electiontype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='logs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='participate',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='permissions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='submit',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'managed': False},
        ),
    ]
