# Generated by Django 4.0.5 on 2022-06-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_photo',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
