# Generated by Django 4.0.5 on 2022-06-16 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_candidate_options_alter_election_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidate',
            table='Candidate',
        ),
        migrations.AlterModelTable(
            name='election',
            table='Election',
        ),
        migrations.AlterModelTable(
            name='electionprogress',
            table='ElectionProgress',
        ),
        migrations.AlterModelTable(
            name='electiontype',
            table='ElectionType',
        ),
        migrations.AlterModelTable(
            name='logs',
            table='Logs',
        ),
        migrations.AlterModelTable(
            name='participate',
            table='Participate',
        ),
        migrations.AlterModelTable(
            name='party',
            table='Party',
        ),
        migrations.AlterModelTable(
            name='permissions',
            table='Permissions',
        ),
        migrations.AlterModelTable(
            name='round',
            table='Round',
        ),
        migrations.AlterModelTable(
            name='submit',
            table='Submit',
        ),
        migrations.AlterModelTable(
            name='vote',
            table='Vote',
        ),
    ]
