# Generated by Django 4.0.5 on 2022-06-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_alter_candidate_table_alter_election_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidate',
            table='elections_candidate',
        ),
        migrations.AlterModelTable(
            name='election',
            table='elections_election',
        ),
        migrations.AlterModelTable(
            name='electionprogress',
            table='elections_electionprogress',
        ),
        migrations.AlterModelTable(
            name='electiontype',
            table='elections_electiontype',
        ),
        migrations.AlterModelTable(
            name='logs',
            table='elections_logs',
        ),
        migrations.AlterModelTable(
            name='participate',
            table='elections_participate',
        ),
        migrations.AlterModelTable(
            name='party',
            table='elections_party',
        ),
        migrations.AlterModelTable(
            name='permissions',
            table='elections_permissions',
        ),
        migrations.AlterModelTable(
            name='round',
            table='elections_round',
        ),
        migrations.AlterModelTable(
            name='submit',
            table='elections_submit',
        ),
        migrations.AlterModelTable(
            name='vote',
            table='elections_vote',
        ),
    ]
