# Generated by Django 4.0.5 on 2022-06-20 12:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('0e712ceb-311d-4023-b0cd-1c1645ca6f71'), primary_key=True, serialize=False),
        ),
    ]
