# Generated by Django 4.0.5 on 2022-06-20 12:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_voter_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('35db6537-c292-4db9-ba3e-9b9ae7e190a3'), primary_key=True, serialize=False),
        ),
    ]
