# Generated by Django 4.0.5 on 2022-06-16 14:32

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_voter_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='voter',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
