# Generated by Django 4.0.5 on 2022-06-20 12:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_alter_voter_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('ddd7ad43-6f33-48b8-b0f4-d6864b63231b'), primary_key=True, serialize=False),
        ),
    ]
