# Generated by Django 4.0.5 on 2022-06-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_alter_voter_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='email',
            field=models.EmailField(blank=True, max_length=300),
        ),
    ]
