# Generated by Django 4.0.5 on 2022-06-20 12:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_alter_voter_voter_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='surname',
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('ce82f956-6787-4462-aa9f-a11aca89a3cd'), primary_key=True, serialize=False),
        ),
    ]
