# Generated by Django 4.0.5 on 2022-06-20 12:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_remove_voter_name_remove_voter_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='electoral_number',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('ddf4876d-55ff-4dab-aaee-0fad53f5715d'), primary_key=True, serialize=False),
        ),
    ]
