# Generated by Django 4.0.5 on 2022-06-22 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_voter_electoral_number_alter_voter_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('0fe92d4f-73c6-45f3-88d2-9d247cb2abec'), primary_key=True, serialize=False),
        ),
    ]
