# Generated by Django 4.0.5 on 2022-06-16 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0007_alter_voter_options_voter_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('63a51092-5e4d-4461-8507-d169acb79c1b'), primary_key=True, serialize=False),
        ),
    ]
