# Generated by Django 4.0.5 on 2022-06-22 14:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0008_alter_voter_username_alter_voter_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('5d8dee95-69cb-4c22-a377-35e78435897d'), primary_key=True, serialize=False),
        ),
    ]
