# Generated by Django 4.0.5 on 2022-06-16 20:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0008_alter_voter_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('be2a8031-5f37-4652-a791-5d8fc583e311'), primary_key=True, serialize=False),
        ),
    ]
