# Generated by Django 4.0.5 on 2022-06-16 20:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0009_alter_voter_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('b182aa4c-74bd-4633-860d-cc78fb4e688b'), primary_key=True, serialize=False),
        ),
    ]
