# Generated by Django 4.0.5 on 2022-06-22 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0009_alter_voter_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('173b39e1-ec66-49a9-a328-4dfc242be09d'), primary_key=True, serialize=False),
        ),
    ]
