# Generated by Django 4.0.5 on 2022-06-22 14:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0010_alter_voter_email_alter_voter_voter_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='username',
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('1e6a4f2c-e929-4ce8-b115-2f08213db1b6'), primary_key=True, serialize=False),
        ),
    ]
