# Generated by Django 4.0.5 on 2022-06-16 20:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0010_alter_voter_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('5655e242-47ad-4947-8ca9-6c79b897f6d6'), primary_key=True, serialize=False),
        ),
    ]
