# Generated by Django 4.0.5 on 2022-06-22 14:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0011_remove_voter_username_alter_voter_voter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='username',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='voter',
            name='electoral_number',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('d594d77a-3653-4c7f-8368-4bcc8c054020'), primary_key=True, serialize=False),
        ),
    ]
