# Generated by Django 4.0.5 on 2022-06-16 21:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0011_alter_voter_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('8fcb0a5b-f0ce-40a7-b001-fa1bedfc4088'), primary_key=True, serialize=False),
        ),
    ]
