# Generated by Django 4.0.5 on 2022-06-27 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
        ('authentification', '0012_voter_username_alter_voter_electoral_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='votes',
            field=models.ManyToManyField(to='elections.election'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('61dba7bf-175c-49f1-be93-46644e191c1d'), primary_key=True, serialize=False),
        ),
    ]
