# Generated by Django 4.0.5 on 2022-06-27 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
        ('authentification', '0013_voter_votes_alter_voter_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('0050c1d7-2405-468c-9457-230faa6b5366'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voter',
            name='votes',
            field=models.ManyToManyField(to='elections.round'),
        ),
    ]
