# Generated by Django 4.0.5 on 2022-06-16 21:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0013_alter_voter_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('9302eeec-b53d-4d82-93d8-84ba240e5fc7'), primary_key=True, serialize=False),
        ),
    ]
