# Generated by Django 4.0.5 on 2022-06-27 12:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0014_alter_voter_voter_id_alter_voter_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('94120e19-d2e5-4d5d-a759-bfe645ee639c'), primary_key=True, serialize=False),
        ),
    ]
