# Generated by Django 4.0.5 on 2022-06-17 08:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0014_alter_voter_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('038aa51b-5b55-4756-88f9-9f76369e2de7'), primary_key=True, serialize=False),
        ),
    ]
