# Generated by Django 4.0.5 on 2022-06-17 08:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0015_alter_voter_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('4a5c7993-e40f-4532-9170-7fbbb6e8649b'), primary_key=True, serialize=False),
        ),
    ]
