# Generated by Django 4.0.5 on 2022-06-30 12:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0016_alter_voter_voter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectoralNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electoral_number', models.BigIntegerField(unique=True)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('7ad8f260-c8dd-4562-bb74-6046b353d6ed'), primary_key=True, serialize=False),
        ),
    ]
