# Generated by Django 4.0.5 on 2022-06-30 12:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0017_electoralnumbers_alter_voter_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('ef01de38-9c84-4eca-8ea2-2acd90996a62'), primary_key=True, serialize=False),
        ),
    ]
