# Generated by Django 4.0.5 on 2022-06-30 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0018_alter_voter_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_id',
            field=models.UUIDField(default=uuid.UUID('00aacae7-263d-4854-b662-4011d748b182'), primary_key=True, serialize=False),
        ),
    ]
